var osc_data = [
[ '1233', 'Schnak', '<a href="https://github.com/schn4ck/schnack">[link]</a>', '<a href="https://schnak.cool">[link]</a>', '8', 'Node.js', '?', '?', 'github, google, twitter, facebook', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '', ],
[ '3277', 'Isso', '<a href="https://github.com/posativ/isso/">isso</a>', '<a href="https://posativ.org/isso/">[1]</a>, <a href="https://lisakov.com/en/blog/acestream-ubuntu-16.04/">[2]</a>, <a href="https://pantarei.xyz/posts/isso-with-social-network-integration/">[3]</a>, <a href="https://vincent.bernat.im/en/blog/2018-more-privacy-blog">[4]</a>, this page', '137', 'python', 'SQLite', 'yes', 'No, but see <a href="https://github.com/posativ/isso/issues/240">fork</a> and its <a href="https://pantarei.xyz/posts/isso-with-social-network-integration/">demo</a>', 'yes', 'within configurable time', 'yes, once', 'simple admin panel: remove/edit comments', 'One level by default, see <a href="https://github.com/posativ/isso/pull/211">PR</a>', 'author only, but see <a href="https://github.com/posativ/isso/pull/443">PR</a>', 'no', 'no', 'yes', 'id-icon', '<a href="https://comment.sh">[link]</a>', 'no', 'no, see <a href="https://github.com/posativ/isso/issues/440">issue</a> for discussion', '?', '?', '?', 'yes', 'yes', 'yes', 'yes', '?', 'no', '?', '?', 'post?, see <a href="https://github.com/posativ/isso/pull/419">PR</a>', 'Used on this page', ],
[ '41', 'comments-app', '<a href="https://github.com/dyu/comments">[link]</a>', '<a href="https://dyu.github.io/comments/">[link]</a>', '92', 'Node.js?', '?', 'yes', 'google, github, gitlab', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', 'yes', '?', '?', '?', '?', '?', '?', '?', '?', '?', 'yes', '?', '?', '?', 'Looks good!', ],
[ '53', 'Realtime comments', '<a href="https://github.com/pusher-community/realtime-commenting">[link]</a>', '<a href="http://realtime-commenting.herokuapp.com/">[link]</a>', '', 'php', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '', ],
[ '160', 'hashover', '<a href="https://github.com/jacobwb/hashover">[link]</a>', '<a href="http://tildehash.com/comments.html">[link]</a>', '', 'php', 'No DB, XML files?', '?', '?', '?', 'yes', 'likes', '?', '?', 'yes', 'yes', '?', '?', 'yes', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', 'yes', '?', ],
[ '117', 'Wildfire', '<a href="https://github.com/cheng-kang/wildfire">[link]</a>', '<a href="https://wildfire.js.org/">[link]</a>', '', 'Vue?', 'Firebase/Wilddog', 'yes', '?', '?', '?', 'Like (for authorized)', 'delete comment, ban', '?', '?', '?', '?', '?', 'For authorized', '?', '?', '?', '?', '?', '?', '?', '?', '?', 'yes', '?', '?', '?', '?', '?', '', ],
[ '0', 'JP_Comment', '<a href="https://github.com/dogloving/JP-Comment">[link]</a>', '<a href="https://raw.githubusercontent.com/dogloving/JP-Comment/master/assets/img/show.gif">[link]</a>', '', 'php', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', 'no', '?', '?', '?', '?', '?', '', ],
[ '9', 'comment-sidecar', '<a href="https://github.com/phauer/comment-sidecar">[link]</a>', '<a href="https://raw.githubusercontent.com/phauer/comment-sidecar/master/screenshot-frontend.png">[link]</a>', '', 'php', 'MySQL', '?', '?', 'yes', '?', '?', '?', '?', 'yes', '?', '?', '?', 'gravatar', '?', '?', '?', 'yes', '?', '?', '?', '?', 'yes', '?', '', '?', '?', '?', '?', 'β', ],
[ '14', 'SitePointNestedComments', '<a href="https://github.com/bodrovis/SitePointNestedComments">[link]</a>', '?', '', 'ruby', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '', ],
[ '418', 'Mouthful', '<a href="https://github.com/vkuznecovas/mouthful">[link]</a>', '<a href="https://mouthful.dizzy.zone/">[1]</a>, <a href="https://dizzy.zone/2018/04/19/I-made-my-own-commenting-server-Here-s-why/">[2]</a>', '44', 'Go', 'dynamodb, MySQL, Postgres', 'yes', 'github, facebook, twitter, vk.com, <a href="https://github.com/vkuznecovas/mouthful/blob/master/examples/configs/README.md#oauth-providers">33 more</a>', '?', 'no', '?', 'yes, admin panel', 'yes', '<a href="https://github.com/vkuznecovas/mouthful/issues/81">not yet</a>', '?', '?', '?', '?', 'no', 'no', 'no', 'yes', 'yes', 'yes', '?', '?', 'yes', 'yes', '?', '?', '?', '?', '?', '', ],
[ '85', 'External-comments', '<a href="https://github.com/skx/e-comments">[link]</a>', '?', '', 'ruby', 'SQLite/Redis', '?', '?', '?', '?', '?', 'No admin panel', 'configurable', 'No', 'yes', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', 'yes', 'jQuery, mustache.js', '?', '?', '?', '?', '', ],
[ '195', 'talkatv', '<a href="https://github.com/talkatv/talkatv">[link]</a>', '?', '', 'python', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '', ],
[ '24', 'Squabble', '<a href="https://github.com/savaslabs/squabble">[link]</a>', '<a href="https://savaslabs.com/2016/10/25/deploy-jekyll-with-travis.html">[link]</a>', '', 'php', 'SQLite', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', 'yes', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '', ],
[ '21', 'Diskuto', '<a href="https://github.com/rejectedsoftware/diskuto">[link]</a>', '<a href="https://raw.githubusercontent.com/rejectedsoftware/diskuto/master/screenshot.png">[link]</a>', '', '<a href="https://en.wikipedia.org/wiki/Vibe.d">Vibe.d</a> (<a href="https://en.wikipedia.org/wiki/D_programming_language">D</a>)', 'MongoDB', '?', '?', 'yes', '?', 'yes', '?', 'yes', '?', '<a href="antihttps://github.com/rejectedsoftware/antispam">yes</a>', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '', ],
[ '955', 'coralproject_talk', '<a href="https://github.com/coralproject/talk">[link]</a>', '?', '', 'Node.js', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', 'yes', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '', ],
[ '1051', 'Staticman', '<a href="https://github.com/eduardoboucas/staticman">[link]</a>', '<a href="https://eduardoboucas.com/blog/2016/08/10/staticman.html">[1]</a>, <a href="https://hugo.staticman.net/post/my-entry/">[2]</a>', '', 'Node.js', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', 'Comments are static, i.e. they are in the html', ],
[ '127', 'CommentWithReplyView', '<a href="https://github.com/Moosphan/CommentWithReplyView-master">[link]</a>', '<a href="https://raw.githubusercontent.com/Moosphan/CommentWithReplyView-master/d8abe02ccb0ca42d40f330ab3f3c68cbad4af029/CommentWithReplyList/art/comment_sample.gif">[link]</a>', '', 'Java', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', 'no', '?', '?', '?', '?', '?', '', ],
[ '488', 'Valine', '<a href="https://github.com/xCss/Valine">[link]</a>', '<a href="https://valine.js.org/en/index.html">[link]</a>', '68', 'Node.js', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', 'gravatar', '?', '?', '?', '?', '?', '?', '?', '?', '?', 'yes', '?', '?', '?', '?', '?', '', ],
[ '576', 'Remark', '<a href="https://github.com/umputun/remark">[link]</a>', '<a href="https://remark42.com/demo/">[link]</a>', '', 'Go', '?', 'yes', '?', '?', '?', 'yes', 'remove comments, block users', '?', '?', '?', '?', '?', 'yes', '?', 'yes', 'yes', 'yes', '?', '?', '?', '?', 'yes', 'yes', '?', '?', '?', '?', 'all comments, post', '', ],
[ '1027', 'Juvia', '<a href="https://github.com/phusion/juvia">[link]</a>', '?', '', 'ruby', '?', '?', '?', '?', '?', '?', 'yes, full-featured admin panel for multiple users', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '', ],
[ '202', 'hashover-next', '<a href="https://github.com/jacobwb/hashover-next">[link]</a>', '?', '', 'php', 'SQLite?', 'yes', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', 'yes', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', 'Is it in working state?', ],
[ '2691', 'Commento', '<a href="https://github.com/adtac/commento">[link]</a>', '<a href="https://demo.comment.io">commento</a>', '16', 'Go', 'SQLite', 'yes', 'google', '?', 'no', '?', '?', 'yes', '?', '?', '?', 'no?', 'yes', 'currently in <a href="https://commento.io">private&nbsp;β</a>', 'yes', '?', '?', '?', '?', '?', '?', 'yes', 'yes', '?', '?', 'None', 'None', '?', '', ],
[ '35', 'Master comments', '<a href="https://github.com/ionutvmi/master-comments-system">[link]</a>', '<a href="https://camo.githubusercontent.com/54fabf226fb3854c18382596ddf76315274020cb/687474703a2f2f7075752e73682f334f3639562e706e67">[link]</a>', '', 'php', 'MySQL', '?', '?', '?', 'yes', '?', 'Edit, delete, ban', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '', ],
[ '33', 'jskomment', '<a href="https://github.com/monperrus/jskomment">[link]</a>', '<a href="https://www.monperrus.net/martin/open+source+ajax+commenting+system">[link]</a>', '', 'AJAX', '?', '?', '?', '?', '?', '?', '?', '?', 'yes?', 'captcha', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', '?', 'Frightening css', ],
]
var cols=[
{title: "Github ★"}, 
{title: "Name"}, 
{title: "Github"}, 
{title: "Demo"}, 
{title: "js, kB"}, 
{title: "Language"}, 
{title: "Database"}, 
{title: "Markdown support"}, 
{title: "Social network login"}, 
{title: "Anonymous comments"}, 
{title: "User can edit"}, 
{title: "User can vote"}, 
{title: "Moderation"}, 
{title: "Nested comments"}, 
{title: "Mail notification"}, 
{title: "Antispam"}, 
{title: "Bad words list"}, 
{title: "Uses cookies"}, 
{title: "Avatar"}, 
{title: "Provided hosting"}, 
{title: "Collapse comments"}, 
{title: "Configurable order"}, 
{title: "Docker container"}, 
{title: "Paging"}, 
{title: "Limit amount of comments per time"}, 
{title: "Hide long threads"}, 
{title: "Import from wordpress"}, 
{title: "Import from disqus"}, 
{title: "English documentation"}, 
{title: "Dependencies"}, 
{title: "Display images"}, 
{title: "Updated"}, 
{title: "Created"}, 
{title: "RSS"}, 
{title: "Note"}, 
]
